language: node_js
node_js:
  - "5.4"
  - "5.2"
  - "5.0"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
before_install:
  - modprobe vcan
  - ip link add type vcan
  - ip link set up vcan0
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
